[tasks.clean-cargo]
private = true
script = '''
find . -type d -name target | xargs rm -rf
'''

[tasks.clean-node_modules]
private = true
script = '''
find . -type d -name node_modules | xargs rm -rf
'''
