extend = [
  { path = "./makefiles/build.toml" },
  { path = "./makefiles/check.toml" },
  { path = "./makefiles/clean.toml" },
  { path = "./makefiles/development.toml" },
  { path = "./makefiles/docker.toml" },
  { path = "./makefiles/lint.toml" },
  { path = "./makefiles/start.toml" },
]

env_files = [{ path = ".env" }, { path = ".env.development", profile = "development" }]

[env]
ORGANIZATION_NAME="lyre"
LOCAL_DOCKER_REGISTRY_AS_PROXY = { value = "localhost:60471", condition = { env_not_set = ["LOCAL_DOCKER_REGISTRY_AS_PROXY"] } }