extend = [
  { path = "./makefiles/build.toml" },
  { path = "./makefiles/check.toml" },
  { path = "./makefiles/clean.toml" },
  { path = "./makefiles/development.toml" },
  { path = "./makefiles/lint.toml" },
  { path = "./makefiles/start.toml" },
]

env_files = [{ path = ".env" }, { path = ".env.development", profile = "development" }]
