extend = [{ path = "./internal/build.toml" }]

[tasks.build]
clear = true
run_task = [
  { name = ["build-tailwind", "build-app"], condition = { profiles = [
    "development",
  ] } },
  { name = "build-app", condition = { profiles = [
    "release",
    "release-ci",
  ] } },
]
